### ISSUE TITLE
Don't know how 'addGlChild' is called，need help.

### ISSUE THREAD

**Issue by loqinyahuive** [eddow/vue-golden-layout#10]

**Comment by eddow** [comment]
Hi,

I did push a new exemple file. I did insert the place and way to call `AddGlChild` if you _really_ wish to do so.
Indeed, working with Vue, it is easier to use Vue' logic as I implemented here: no child is added nor removed, but children are an image of an array of the model (described in the template) an the array is changed.

**Comment by loqinyahuive** [comment]
I want to register a new component, not to iterate the components. I think I still need know how to call the 'addGlChild'.

Thanks a lot!

**Comment by eddow** [comment]
Well, it's as you wish, the example also uses a v-if.
Also, a gl-component can contain a <div :is="..."> .
