### ISSUE TITLE
addGlChild access

### ISSUE THREAD

**Issue by ng5** [eddow/vue-golden-layout#11]
Hi,
I have read the previous issue on this topic, it is not clear how to access this programmatically. I'm not too much familiar with type script and may be I'm missing something basic. 

After I registered vgl object with Vue.use(vgl), how do I then access components like layoutGolden, glRow, glCol etc, they are all undefined with vgl.layoutGolden, vgl.glRow etc. 

I can see them defined in Closure section under chrome developer console for vgl Object. Would appreciate any help on this.

Application I'm working with is a financial application where different layout has to be loaded selected by user. For example if there are 10 Vue Components ( Portfolio, Watchlist, Pricing) that are available under standard Vue Router, but user needs ability to view them simultaneously and added to a layout. 

Thanks

**Comment by eddow** [comment]
Hello,
I finally found some incentive to make this control that seems quite natural to have indeed.

The library now contains a control `golden-router`. I let you read README.md but basically it is what you aimed to do.

Please, feel free to contribute to that control even by just giving suggestions.

**Comment by ng5** [comment]
thank you for looking into this. I'm no longer using golden layout and instead using native CSS grid, which are good enough for my current purpose. 

Here is a simple Plunkr to demonstrate drag/drop/swap feature of CSS grid - https://plnkr.co/0AQHX5

In our project, we found that golden layout (Javascript version) is good if you have one main dashboard layout (only 1 instance of golden layout is created), but if you allow multiple golden layout containers selected by user, then somewhere along the line it results in memory leak, even after explicitly calling close() method on container and destroy() method on golden layout.

If you compare features provided by golden layout compared to native CSS grid layout, this is what i've found. 

1. Container Resize - Only provided by golden layout
2. Multiple tabs in one container - Only provided by golden layout
3. Drag and Drop - Can be easily done using CSS grid
4. Load/Store layout - Can be easily done by CSS grid

Given that i'm missing out on 2 features, but this is not a show stopper for us, because users are happy with pre-built layouts available to them via CSS grid.

Regards,
Rohit
