### ISSUE TITLE
Help needed : weird bug

### ISSUE THREAD

**Issue by jfmmm** [eddow/vue-golden-layout#12]
I'm having this weird bug where if I drag a window and merge them with other they leave an empty space behind.. the panel don't resize automaticaly to take all the place available like they do in the GL demo on their website.

I made a MWE here with the code you had in the test folder. You can reproduce by moving CompB and CompC into compA. and then dynamic1 into compA.. and so on eventually you are left with a small window of the minimum size possible for your content and the title.

https://codesandbox.io/s/jv4p0vv1ry

Also if you look into the dependency of that demo you can see I had to add vue-property-decorator to make it work. I think you should add this as a dependecy of your npm module.

Thanks!

**Comment by jfmmm** [comment]
I must be explaining myself wrong. I'm am not talking about the last panel draged not having a tab.

I'm talking about the panel left behind after I remove one not behing resized to take the full width and height of the container.

here a better example:

![test2](https://user-images.githubusercontent.com/2498456/42064442-43e8de72-7b04-11e8-9faf-4aa0f73fe8b5.gif)

at the end after I deleted the 3 other panel, comA should be taking the full size of the container like it does here on the official golden layout demo.

![test3](https://user-images.githubusercontent.com/2498456/42064622-f600d556-7b04-11e8-91e0-2726b205c368.gif)

**Comment by eddow** [comment]
Indeed, this will be worth investigation.

**Comment by eddow** [comment]
So, I am sorry not to have much time nowadays to investigate by myself.
I noticed that, if you play a bit and displace all the elements in new places, they begin to act as expected.

The problem seems therefore to come from the way it is initialised. What should be done is a comparison of the configuration before and after re-doing the layout with d&d.

If noone found nothing, I'll be able to investigate more within next month.

**Comment by jfmmm** [comment]
> So, I am sorry not to have much time nowadays to investigate by myself.

No problem, this is for a personal project, so it isn't time sensitive.

> I noticed that, if you play a bit and displace all the elements in new places, they begin to act as expected.

Only seem to get worse for me. But it would make sense that the problem would be in the initialization 🤔 

Thanks for looking into this. Might take a look too, but last time I tried my begineer level in vue syntax was very confused with all the typescript decorator.

**Comment by eddow** [comment]
Not from my side. I am working actively on the library but on more urgent ($) issues.

**Comment by eddow** [comment]
Hey guys,

Finally, having a chat about that bug, I notoced that the stacks here are not closable (they don't have the closing cross)

In the example, it makes sense as elements can be added to these stacks dynamically - if you use it in another context, don't hesitate to mark a disposable stack as closable : `<gl-stack :closable="true">`

**Comment by martincarles** [comment]
Thanks @eddow, your work is much appreciated!
