### ISSUE TITLE
Vue and Vue-Router should be handled as PeerDependencies

### ISSUE THREAD

**Issue by AtofStryker** [eddow/vue-golden-layout#14]
Hello @eddow

I am using a lerna monorepo where I have a subpackage installing vue-golden-layout. I have Vue and other Vue dependencies installed in the root/workspace directory. The problem I am running into is vue-golden-layout is installing Vue and Vue-Router within the subpackage and not resolving to the appropriate vue dependency.

I can provide an example if needed.

I was thinking, it would probably make more sense to change:

"dependencies": {
    "golden-layout": "^1.5.8",
    "jquery": "^3.2.1",
    "vue": "^2.5.16",
    "vue-property-decorator": "^6.0.0",
    "vue-resize-directive": "^1.0.0",
    "vue-router": "^3.0.1"
  }

to :

"dependencies": {
    "golden-layout": "^1.5.8",
    "jquery": "^3.2.1",    
    "vue-property-decorator": "^6.0.0",
    "vue-resize-directive": "^1.0.0"   
  },
peerDependencies: {
 "vue-router": "^3.0.0",
 "vue": "^2.5.0",
}

that way, consumers are prompted to install vue and vue router, but it isnt installed for them. Hopefully this is ok and look forward to your feedback!

**Comment by eddow** [comment]
Hello,

I even didn't know about "peerDependencies", thank you very much.

**Comment by AtofStryker** [comment]
Thanks @eddow! Pulled in this morning and looks great!
