### ISSUE TITLE
Class attribute on<glComponent>remains the same

### ISSUE THREAD

**Issue by trszdev** [eddow/vue-golden-layout#17]
`<glComponent class="some-class" />` not working, an element will always have .glComponent class

**Comment by eddow** [comment]
Well, [this](https://github.com/eddow/vue-golden-layout/blob/eda126c2a42b6883a0136ce3d0b76c08990e7261/src/gl-component.vue#L35) indeed is a challenge; as we host components in div-s and displace them afterward, letting the `div {display: none;}` behind, we would have to take the classes and styles from this `div {display: none;}` to the component.

I am first sorry to answer so late, and also letting it opened for help : I have no clue yet how to watch the classes and style of an element to duplicate it on an other.

**Comment by eddow** [comment]
Finally, I discovered by mistake an over-simplified solution : I was just over-wrapping my divs. The class is now applied.
