### ISSUE TITLE
Unable to restore rows...?

### ISSUE THREAD

**Issue by xeor** [eddow/vue-golden-layout#18]
I am playing with the save/restore functionality. It works for columns, but if I drag one item under the other, the button one won't get restored.

I tested this with the current test/ project.

1. Setup the test
2. Make sure the `browserGL` local storage is deleted.
3. Refresh page
4. Click add
5. Drag the new `dynamic 2` so it is below `dynamic 1`
```
 |----------------------|
 | Comp A  | dynamic1   |
 |         |------------|
 |         | dynamic2   |
 |---------|------------|
```
6. Refresh..
7. dynamic2 is now gone...

This happens only when adding new items as a new row.. Adding them on the side works fine. Also, adding it as a new row spanning both compA and dynamic1 seams to work..

I am a little unsure, but I am pretty sure this have worked from time to time when I have tested other things in `vue-golden-layout`, however, I can't get it to work at all now...

**Comment by xeor** [comment]
It is the TODO @ https://github.com/eddow/vue-golden-layout/blob/21799eba2e26d37732b78c0fddfb1d4f9679e209/src/golden.vue#L148 that causes this.. 

Using
```
localStorage["browserGL"] = JSON.stringify(
  this.$refs.topGl.gl.toConfig()
);
```
in the example solves the problem..

**Comment by eddow** [comment]
Hi,
There were many improvements done lately on saving/restoring state. Could you please check if your issue is still valid with the last version?

**Comment by dorinoltean** [comment]
I tried to reproduce this issue in a clean local storage env. dynamic2 still exists after refresh.

**Comment by eddow** [comment]
I'll close the bug for now, please feel free to re-open if it tests wrong
