### ISSUE TITLE
Cannot use the plugin: Critical dependency -> require function is used in a way in which dependencies cannot be statically extracted

### ISSUE THREAD

**Issue by jensnilsson** [eddow/vue-golden-layout#2]
Hi,

When trying to use the library I get the following error:

```
WARNING  Compiled with 2 warnings                                    6:36:17 PM

 warning  in ./~/vue-golden-layout/dist/vue-golden-layout.js

16186:1091-1101 Critical dependency: the request of a dependency is an expression

 warning  in ./~/vue-golden-layout/dist/vue-golden-layout.js

16186:5048-5055 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
```
Similar issue is found on: https://github.com/dcodeIO/protobuf.js/issues/339

Webpack cannot install due to require.

My code:

```
import Vue from 'vue'
import vgl from 'vue-golden-layout'
import Vuetify from 'vuetify'
import App from './App'
import router from './router'

Vue.use(vgl)
Vue.use(Vuetify)

Vue.config.productionTip = false

/* eslint-disable no-new */
new Vue({
  el: '#app',
  router,
  render: h => h(App)
})
```

```
<layout-golden>
        <gl-col>
          <gl-component @resize="console.log('resize')" title="compA">
            <h1>CompA</h1>
          </gl-component>
          <gl-component @resize="console.log('resize')" title="compB">
            <h1>CompA</h1>
          </gl-component>
        </gl-col>
</layout-golden>
```
What was done:

1: npm install --save vue-golden-layout
2: added code 1 and code 2
3. npm run dev

Comment on instructions:

In repo it says to also run
- npm install
- npm run compile

I did that in root folder: 
- npm install says up to date, 
- npm run compile says missing script compile

I did that in node_modules/vue-golden-layout but that gives errors too.

I have:
node version: 5.3
webpack: 2.3.3
vue: 2.3.4

**Comment by eddow** [comment]
Indeed, yes, I did let a non-working version as I was testing with npm at a moment, I have to check back some things - I forgot about this library :-/

**Comment by eddow** [comment]
So,

A library I used just added a change to allow webpack bundling among other things; I deployed with the new version.
Please, give a try with the new version published for test.
If it doesn't work yet, could you please provide test project with webpack config and what is needed?

**Comment by shiyafei** [comment]
I have a vue && webpack project which use vue-cli init, how I use this layout

**Comment by eddow** [comment]
Hi, so,
The library had a major bundling improvement - this means we can be sure now it can be used without internal conflicts (without even warnings).
Please try again and come back if you have further problems.
