### ISSUE TITLE
glStack dynamically created from an array stops working if any gl component is moved

### ISSUE THREAD

**Issue by dorinoltean** [eddow/vue-golden-layout#21]
If we dynamically create components inside a glStack from an array. And later on, we move one of the tabs from UI into a different stack. Adding a new item to array throws an exception because the length if the array is now N and the number of tabs in the glStack is N-1

![dynamicstack](https://user-images.githubusercontent.com/1523651/47851468-649a1600-dde1-11e8-88d4-4baca9478cee.gif)

**Comment by eddow** [comment]
Thanks for report!
https://github.com/eddow/vue-golden-layout/commit/433d130f5d8ff3d68ab39d022c155f6ddc6b362a#diff-89003498012943337bed7c16419c0955
