### ISSUE TITLE
Adding Dynamic components with v-for

### ISSUE THREAD

**Issue by VasilisNikiforidis** [eddow/vue-golden-layout#26]
Hi!
I am trying to dynamically add gl-components by looping another component. Essentially, I want to create multiple tabs each with different content created by another component. 
My code: 
..... (gl-component is correctly used inside its layout and stack, omitted because of irrelevance)
```
<template v-if="getActiveUnit">
   <gl-component v-for="(key,index) in get_units"
     :title="get_units_names(index)" 
     :key="index">
           
         <Editor :unitInd="index"></Editor>
//unitInd is bound here to be used inside the Editor component
            
   </gl-component>
</template>
```
....... 
My problem is, that while my code runs without errors and produces my expected result, it raises the warning (one time for each loop) "Dynamic golden-layout components should be named templates instead.", which are slowing down the loading of my app.

I have read the documentation on why this happens and tried to implement the instructions, but unfortunately there are no examples and I could not get it to work. For example, when I pass 'slot = "anyname" ' in the template and 'template="anyname" ' in the gl-component, nothing shows on my screen.

I am relatively new to Vue so please bear with me and thanks in advance for any suggestions!

**Comment by eddow** [comment]
Hello,

This is explained here : https://github.com/eddow/vue-golden-layout#named-templates
As the gl-component is added/removed dynamically, it should reference a named template, here is how to do.
- Have in the `golden-layout` a template defined ith a name (here "myTemplate")
```vue
<template slot="myTemplate" :slot-scope="{index}">
         <Editor :unitInd="index"></Editor>
//unitInd is bound here to be used inside the Editor component
</template>
```
- After, reference it in the `gl-component`
```vue
<gl-component v-for="(key,index) in get_units"
     :title="get_units_names(index)" 
     :key="index"
     template="myTemplate" :state="{index}" />
```

**Comment by VasilisNikiforidis** [comment]
I have already tried this but it does not work, because if I have the template defined before the element,     
 "{index}" raises an error since it is not defined before reference and if I define the template nested inside the gl-component, the template property of the gl-component raises an error since "myTemplate" is not defined

**Comment by eddow** [comment]
There is a working example in test/test.vue where the slot used is `stackCtr`
