### ISSUE TITLE
$fsx is not defined

### ISSUE THREAD

**Issue by shiyafei** [eddow/vue-golden-layout#4]
1、npm install -g vue-cli
2、vue init webpack TEST
3、cd TEST
4、npm install
5、npm install vue-golden-layout --D
6、In router/index.js， Add 
```
import vgl from 'vue-golden-layout'  
Vue.use(vgl)
```

7、In App.vue template，change to  
```
<layout-golden>
    <gl-col>
        <gl-component @resize="console.log('resize')" title="compA">
        <h1>CompA</h1>
        </gl-component>
        <gl-component @resize="console.log('resize')" title="compB">
        <h1>CompA</h1>
        </gl-component>
    </gl-col>
</layout-golden>
```
8、npm run dev
9、open browser,

```
vue-golden-layout.js?7dee:695 Uncaught ReferenceError: $fsx is not defined
    at eval (eval at <anonymous> (app.js:1116), <anonymous>:695:4)
    at Object.<anonymous> (app.js:1116)
    at __webpack_require__ (app.js:689)
    at fn (app.js:110)
    at eval (eval at <anonymous> (app.js:974), <anonymous>:4:76)
    at Object.<anonymous> (app.js:974)
    at __webpack_require__ (app.js:689)
    at fn (app.js:110)
    at eval (eval at <anonymous> (app.js:878), <anonymous>:5:66)
    at Object.<anonymous> (app.js:878)
```

**Comment by eddow** [comment]
Yhup,
So, a dependency was buggy.
The new tested version of the library is available on NPM and the working webpack config is here : 
https://github.com/eddow/vue-golden-layout/blob/master/test/compile.js

**Comment by shiyafei** [comment]
I re-git pull the latest code, however when npm install , a error is :
```
npm ERR! addLocal Could not install /home/shiyafei/vue-golden-layout/.yalc/fuse-box

```
I found code in package.json is "fuse-box": "file:.yalc/fuse-box" , but no .yalc file in directory

**Comment by eddow** [comment]
Finally, it has been done - you should be able to git-pull, npm-install, node-fuse
