### ISSUE TITLE
The height cannot work.

### ISSUE THREAD

**Issue by loqinyahuive** [eddow/vue-golden-layout#8]
<gl-component title="compA" height="500">
     <h1>CompA</h1>
</gl-component>

**Comment by loqinyahuive** [comment]
When I use 'gl-component', height is assigned 500 and the height of the component is still 0.

**Comment by shiyafei** [comment]
@loqinyahuive 
Did you solve it ? I also encountered this problem

**Comment by loqinyahuive** [comment]
@shiyafei This problem has been solved.  Do you need help? Add a class for the <layout-golden class="screen"> tag. eg:  <style>.screen {width: 100vw, height: 100vh}</style>

**Comment by shiyafei** [comment]
@loqinyahuive 
Thank you very much !
