### ISSUE TITLE
vue warn 

### ISSUE THREAD

**Issue by zhump** [eddow/vue-golden-layout#9]
[vue-class-component] Component class must inherit Vue or its descendant class when class property is used.

**Comment by eddow** [comment]
Hello,
Could you please provide a context?
Like - when do you receive this message?

**Comment by eddow** [comment]
note: Found it, it will definitely not be a priority be I let it opened if I or whoever wonder what to do on an afternoon.
Basically, the problem is the inheritance in a typescript file from a SFC

**Comment by eddow** [comment]
Finally, after one year, I got sick of playing with fuse-box who is quite not adapted to libraries writing - I switched to webpack and all these bugs could be solved.
Note: now, vue-golden-layout HAS to be packed with the esm version of vue.
